version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.8.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "PreNativeCmsPublicationEvents:2:2,PreNativeCmsMetadataPublicationEvents:2:2"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  cms-notifier:
    image: nexus.in.ft.com:5000/coco/cms-notifier
    container_name: cms-notifier
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: "PreNativeCmsPublicationEvents"
      KAFKA_FORWARDING_TOPIC: "PreNativeCmsMetadataPublicationEvents"
      CONTENT_TYPE: "Content"
      FORWARDING_CONTENT_TYPE: "Annotations"
    ports:
      - "8081:8080"
      - "8082:8081"
    depends_on:
      - kafka

  app:
    build: .
    image: native-ingester:local
    container_name: native-ingester
    environment:
      NATIVE_CONTENT_UUID_FIELDS: "uuid,post.uuid,data.uuidv3,id"
      CONFIG: "config.json"
      Q_READ_GROUP: "nativeIngesterCms"
      Q_READ_ADDR: "zookeeper:2181"
      Q_READ_TOPIC: "PreNativeCmsPublicationEvents"
      Q_WRITE_ADDR: "kafka:9092"
      Q_WRITE_TOPIC: "NativeCmsPublicationEvents"
    ports:
      - "8080:8080"
    depends_on:
      - cms-notifier
    command: /native-ingester
