version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

jobs:
  build:
    working_directory: /native-ingester
    docker:
      - image: golang:1
        environment:
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
      - image: blacktop/kafka:0.8
        environment:
          KAFKA_BROKER_ID: 1
    steps:
      - checkout
      - ft-golang-ci/build
      - ft-golang-ci/lint
      - ft-golang-ci/test

workflows:
  tests_and_docker:
    jobs:
      - build
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context: cm-team-snyk
