# Default values for native-ingester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"
image:
  repository: coco/native-ingester
  pullPolicy: IfNotPresent
env:
  CONFIG: "" # This should be defined in the specific app-configs folder
  CONSUMER_GROUP: "" # This should be defined in the specific app-configs folder
  CONSUMER_TOPIC: "" # This should be defined in the specific app-configs folder
  NATIVE_CONTENT_UUID_FIELDS: "" # This should be defined in the specific app-configs folder
  PRODUCER_TOPIC: "" # This should be defined in the specific app-configs folder
  PANIC_GUIDE_URL: "" # This should be defined in the specific app-configs folder
  LOG_LEVEL: "INFO"
