# Default values for native-ingester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
image:
  repository: coco/native-ingester
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 256Mi
env:
  QUEUE_READ_GROUP: "" # This should be defined in the specific app-configs folder
  QUEUE_READ_TOPIC: "" # This should be defined in the specific app-configs folder
  NATIVE_CONTENT_UUID_FIELDS: "" # This should be defined in the specific app-configs folder
  NATIVE_RW_COLLECTIONS_BY_ORIGINS: "" # This should be defined in the specific app-configs folder
  QUEUE_WRITE_TOPIC: "" # This should be defined in the specific app-configs folder
