apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APP_NAME
          value: {{ .Values.service.name }}
        - name: LOG_LEVEL
          value: "{{ .Values.env.LOG_LEVEL }}"
        - name: KAFKA_CLUSTER_ARN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: msk.kafka.cluster.arn
        - name: KAFKA_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: msk.kafka.broker.url
        - name: CONFIG
          value: {{ .Values.env.CONFIG }}
        - name: CONSUMER_GROUP
          value: {{ .Values.env.CONSUMER_GROUP }}
        - name: CONSUMER_TOPIC
          value: {{ .Values.env.CONSUMER_TOPIC }}
        - name: NATIVE_CONTENT_UUID_FIELDS
          value: {{ .Values.env.NATIVE_CONTENT_UUID_FIELDS }}
        - name: CONTENT_TYPE
          value: {{ .Values.env.CONTENT_TYPE }}
        - name: NATIVE_RW_ADDRESS
          value: "http://nativerw:8080"
        - name: PRODUCER_TOPIC
          value: {{ .Values.env.PRODUCER_TOPIC }}
        - name: KAFKA_LAG_TOLERANCE
          value: "{{ .Values.env.KAFKA_LAG_TOLERANCE }}"
        - name: PANIC_GUIDE_URL
          value: {{ .Values.env.PANIC_GUIDE_URL }}
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}

