# Values used for the deployed application.
replicaCount: 2
service:
  name: native-ingester-metadata
env:
  QUEUE_READ_GROUP: "nativeIngesterMetadata"
  QUEUE_READ_TOPIC: "PreNativeCmsMetadataPublicationEvents"
  NATIVE_CONTENT_UUID_FIELDS: "uuid,post.uuid,data.uuidv3,id"
  CONFIG_FILE: "config_metadata.json"
  QUEUE_WRITE_TOPIC: "NativeCmsMetadataPublicationEvents"
  CONTENT_TYPE: "Annotations"
resources:
  requests:
    memory: 200Mi
  limits:
    memory: 512Mi