# Values used for the deployed application.
replicaCount: 2
service:
  name: native-ingester-metadata
env:
  QUEUE_READ_GROUP: "nativeIngesterMetadata"
  QUEUE_READ_TOPIC: "PreNativeCmsMetadataPublicationEvents"
  NATIVE_CONTENT_UUID_FIELDS: "uuid,post.uuid,data.uuidv3,id"
  NATIVE_RW_COLLECTIONS_BY_ORIGINS: "\"{\\\"http://cmdb.ft.com/systems/methode-web-pub\\\": \\\"v1-metadata\\\", \\\"http://cmdb.ft.com/systems/pac\\\":\\\"pac-metadata\\\", \\\"http://cmdb.ft.com/systems/next-video-editor\\\":\\\"video-metadata\\\"}\""
  QUEUE_WRITE_TOPIC: "NativeCmsMetadataPublicationEvents"
  CONTENT_TYPE: "Annotations"
resources:
  requests:
    memory: 200Mi
  limits:
    memory: 512Mi