# Values used for the deployed application.
replicaCount: 1
service:
  name: native-ingester-cms
env:
  CONSUMER_GROUP: "native-ingester-cms"
  CONSUMER_TOPIC: "PreNativeCmsPublicationEvents"
  NATIVE_CONTENT_UUID_FIELDS: "uuid,post.uuid,data.uuidv3,id"
  CONFIG: "config.json"
  PRODUCER_TOPIC: "NativeCmsPublicationEvents"
  PANIC_GUIDE_URL: "https://runbooks.in.ft.com/native-ingester"
  KAFKA_LAG_TOLERANCE: 500
resources:
  requests:
    memory: 250Mi
  limits:
    memory: 512Mi
